# Generated by Django 4.0.3 on 2022-03-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.RemoveField(
            model_name='projects',
            name='provider',
        ),
        migrations.AddField(
            model_name='projects',
            name='skills',
            field=models.ManyToManyField(blank=True, to='home.skills', verbose_name='Habilidades'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos', verbose_name='imagen'),
        ),
    ]
